# Generated by Django 4.2.29 on 2026-03-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_checked_in', models.BooleanField(default=False)),
                ('room', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('overenrollment_cap', models.IntegerField()),
                ('registration_open', models.BooleanField(default=True)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OnsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_registration_open', models.BooleanField(default=True)),
                ('default_overenrollment_cap', models.IntegerField(default=5)),
                ('event_name', models.CharField(default='Splash 2026', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_grade', models.IntegerField()),
                ('checked_in', models.BooleanField(default=False)),
                ('esp_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='onsite.esp_class')),
            ],
        ),
    ]
